name: Snyk Monitor - Pipenv
on:
  push:
    branches: [ master, main ]
jobs:
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      # Checkout Code
      - uses: actions/checkout@v1 

      # Node and NPM
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: sudo npm install -g snyk
      - run: snyk auth "$SNYK_TOKEN"

      # Python and Pipenv
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      # Monitor
      - name: Snyk Monitor
        run: snyk monitor --all-projects --remote-repo-url=${{ github.event.repository.name }} --org=goofy-co.

      # - name: Generate PyPi manifests
      #   run: |
      #     find . -name "Pipfile.lock" | while read line ; do (cd ${line%/*} && python3 -m pipenv lock -r > requirements.txt) ; done
