name: Snyk Monitor - Pipenv
on:
  push:
    branches: [ master, main ]
jobs:
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install NPM
        run: npm install

      - name: Install Snyk
        run: sudo npm install -g snyk

      # - name: Generate PyPi manifests
      #   run: |
      #     find . -name "Pipfile.lock" | while read line ; do (cd ${line%/*} && python3 -m pipenv lock -r > requirements.txt) ; done

      - name: Snyk Authenticate
        run: snyk auth "$SNYK_TOKEN"
      - name: Snyk Test
        run: snyk monitor --all-projects --remote-repo-url=${{ github.event.repository.name }} --org=goofy-co.


